name: "Broken Link Check"
on:
    schedule:
      - cron: 0 0 1 * * # run monthly
    repository_dispatch: # run manually
      types: [check-link]
    push:
        paths-ignore:
            - .gitignore
            - README.md
            - LICENSE
      
jobs:
    check:
        name: Broken Link Check
        runs-on: ubuntu-latest
        steps:
            - name: Broken Link Check
              uses: technote-space/broken-link-checker-action@v2
              with:
                TARGET: https://creme332.vercel.app/